<?xml version="1.0" encoding="utf-8"?><Database Name="DATHTT" Class="QLTBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Brian-PC;Initial Catalog=DATHTT;User ID=sa" SettingsObjectName="DXApplication1.Properties.Settings" SettingsPropertyName="DATHTTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGBAOGIA" Member="BANGBAOGIAs">
    <Type Name="BANGBAOGIA">
      <Column Name="MABG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHANLOAI" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENBAOGIA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GHICHUBAOGIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="BANGBAOGIA_CHITIETSUACHUA" Member="CHITIETSUACHUAs" ThisKey="MABG" OtherKey="MABG" Type="CHITIETSUACHUA" />
      <Association Name="PHANLOAI_BANGBAOGIA" Member="PHANLOAI" ThisKey="MAPHANLOAI" OtherKey="MAPHANLOAI" Type="PHANLOAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THIETBI" Member="THIETBIs">
    <Type Name="THIETBI">
      <Column Name="MATHIETBI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMODEL" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="SERIAL" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TENTHIETBI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYMUA_SUACHUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHUTHIETBI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="THIETBI_LINHKIEN" Member="LINHKIENs" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="LINHKIEN" />
      <Association Name="THIETBI_PHIEUTIEPNHAN" Member="PHIEUTIEPNHANs" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="PHIEUTIEPNHAN" />
      <Association Name="MODEL_THIETBI" Member="MODEL" ThisKey="MAMODEL" OtherKey="MAMODEL" Type="MODEL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BOPHAN" Member="BOPHANs">
    <Type Name="BOPHAN">
      <Column Name="MABOPHAN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBOPHAN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENGIAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="BOPHAN_NHANVIEN" Member="NHANVIENs" ThisKey="MABOPHAN" OtherKey="MABOPHAN" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MALINHKIEN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHOADON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="HOADON" IsForeignKey="true" />
      <Association Name="LINHKIEN_CHITIETHOADON" Member="LINHKIEN" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="LINHKIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETSUACHUA" Member="CHITIETSUACHUAs">
    <Type Name="CHITIETSUACHUA">
      <Column Name="MACTSC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPSC" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MABG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUAXONG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GHICHUCTSC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MALINHKIEN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="BANGBAOGIA_CHITIETSUACHUA" Member="BANGBAOGIA" ThisKey="MABG" OtherKey="MABG" Type="BANGBAOGIA" IsForeignKey="true" />
      <Association Name="LINHKIEN_CHITIETSUACHUA" Member="LINHKIEN" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="LINHKIEN" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETSUACHUA" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUSUACHUA_CHITIETSUACHUA" Member="PHIEUSUACHUA" ThisKey="MAPSC" OtherKey="MAPSC" Type="PHIEUSUACHUA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETTN" Member="CHITIETTNs">
    <Type Name="CHITIETTN">
      <Column Name="MAPHIEUTN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALINHKIEN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TINHTRANGHUHONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHTHUC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LINHKIEN_CHITIETTN" Member="LINHKIEN" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="LINHKIEN" IsForeignKey="true" />
      <Association Name="PHIEUTIEPNHAN_CHITIETTN" Member="PHIEUTIEPNHAN" ThisKey="MAPHIEUTN" OtherKey="MAPHIEUTN" Type="PHIEUTIEPNHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHOADON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHACHHANG" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAPSC" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="CHITIETHOADON" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKHACHHANG" OtherKey="MAKHACHKHACH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUSUACHUA_HOADON" Member="PHIEUSUACHUA" ThisKey="MAPSC" OtherKey="MAPSC" Type="PHIEUSUACHUA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKHACHKHACH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOMKH" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENKHACHHANG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIACHIKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FAX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMAILKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKHACHKHACH" OtherKey="MAKHACHHANG" Type="HOADON" />
      <Association Name="KHACHHANG_PHIEUTIEPNHAN" Member="PHIEUTIEPNHANs" ThisKey="MAKHACHKHACH" OtherKey="MAKHACHKHACH" Type="PHIEUTIEPNHAN" />
      <Association Name="NHOMKHACHHANG_KHACHHANG" Member="NHOMKHACHHANG" ThisKey="MANHOMKH" OtherKey="MANHOMKH" Type="NHOMKHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LINHKIEN" Member="LINHKIENs">
    <Type Name="LINHKIEN">
      <Column Name="MALINHKIEN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATHIETBI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TENLINHKIEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSX" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYMUA_SUACHUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GHICHULINHKIEN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LINHKIEN_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="CHITIETHOADON" />
      <Association Name="LINHKIEN_CHITIETSUACHUA" Member="CHITIETSUACHUAs" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="CHITIETSUACHUA" />
      <Association Name="LINHKIEN_CHITIETTN" Member="CHITIETTNs" ThisKey="MALINHKIEN" OtherKey="MALINHKIEN" Type="CHITIETTN" />
      <Association Name="THIETBI_LINHKIEN" Member="THIETBI" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="THIETBI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MANHINH" Member="MANHINHs">
    <Type Name="MANHINH">
      <Column Name="MaManHinh" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="PHANQUYENs" ThisKey="MaManHinh" OtherKey="MAMANHINH" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.MODEL" Member="MODELs">
    <Type Name="MODEL">
      <Column Name="MAMODEL" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANSX" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENMODEL" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="THUOC_LOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHUMODEL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MODEL_THIETBI" Member="THIETBIs" ThisKey="MAMODEL" OtherKey="MAMODEL" Type="THIETBI" />
      <Association Name="NHASANXUAT_MODEL" Member="NHASANXUAT" ThisKey="MANSX" OtherKey="MANSX" Type="NHASANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNGNHOMNGDUNG" Member="NGUOIDUNGNHOMNGDUNGs">
    <Type Name="NGUOIDUNGNHOMNGDUNG">
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOMNGDUNG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHANVIEN_NGUOIDUNGNHOMNGDUNG" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNGNHOMNGDUNG" Member="NHOMNGUOIDUNG" ThisKey="MANHOMNGDUNG" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MABOPHAN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENNHANVIEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHINV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMAILNV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LUONG" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHANVIEN_CHITIETSUACHUA" Member="CHITIETSUACHUAs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="CHITIETSUACHUA" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="HOADON" />
      <Association Name="NHANVIEN_NGUOIDUNGNHOMNGDUNG" Member="NGUOIDUNGNHOMNGDUNGs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NGUOIDUNGNHOMNGDUNG" />
      <Association Name="NHANVIEN_PHIEUSUACHUA" Member="PHIEUSUACHUAs" ThisKey="MANHANVIEN" OtherKey="MANHANVIENTIEPNHAN" Type="PHIEUSUACHUA" />
      <Association Name="NHANVIEN_PHIEUSUACHUA1" Member="PHIEUSUACHUAs1" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="PHIEUSUACHUA" />
      <Association Name="NHANVIEN_PHIEUSUACHUA2" Member="PHIEUSUACHUAs2" ThisKey="MANHANVIEN" OtherKey="NGUOIGOI" Type="PHIEUSUACHUA" />
      <Association Name="NHANVIEN_PHIEUTIEPNHAN" Member="PHIEUTIEPNHANs" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="PHIEUTIEPNHAN" />
      <Association Name="BOPHAN_NHANVIEN" Member="BOPHAN" ThisKey="MABOPHAN" OtherKey="MABOPHAN" Type="BOPHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="MANSX" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNSX" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="GHICHUSX" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHASANXUAT_MODEL" Member="MODELs" ThisKey="MANSX" OtherKey="MANSX" Type="MODEL" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMKHACHHANG" Member="NHOMKHACHHANGs">
    <Type Name="NHOMKHACHHANG">
      <Column Name="MANHOMKH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOMKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KHUYENMAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHOMKHACHHANG_KHACHHANG" Member="KHACHHANGs" ThisKey="MANHOMKH" OtherKey="MANHOMKH" Type="KHACHHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHOMNGUOIDUNG" Member="NHOMNGUOIDUNGs">
    <Type Name="NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHOMNGUOIDUNG_NGUOIDUNGNHOMNGDUNG" Member="NGUOIDUNGNHOMNGDUNGs" ThisKey="MANHOM" OtherKey="MANHOMNGDUNG" Type="NGUOIDUNGNHOMNGDUNG" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOMNGDUNG" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHANLOAI" Member="PHANLOAIs">
    <Type Name="PHANLOAI">
      <Column Name="MAPHANLOAI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHANLOAI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PHANLOAI_BANGBAOGIA" Member="BANGBAOGIAs" ThisKey="MAPHANLOAI" OtherKey="MAPHANLOAI" Type="BANGBAOGIA" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MANHOMNGDUNG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="MANHINH" ThisKey="MAMANHINH" OtherKey="MaManHinh" Type="MANHINH" IsForeignKey="true" />
      <Association Name="NHOMNGUOIDUNG_PHANQUYEN" Member="NHOMNGUOIDUNG" ThisKey="MANHOMNGDUNG" OtherKey="MANHOM" Type="NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUSUACHUA" Member="PHIEUSUACHUAs">
    <Type Name="PHIEUSUACHUA">
      <Column Name="MAPSC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANHANVIENTIEPNHAN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAPHIEUTN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYBATDAU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GHICHUPSC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NGUOIGOI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DONGY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GIADUKIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THONGTINSUACHUA" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHIEUSUACHUA_CHITIETSUACHUA" Member="CHITIETSUACHUAs" ThisKey="MAPSC" OtherKey="MAPSC" Type="CHITIETSUACHUA" />
      <Association Name="PHIEUSUACHUA_HOADON" Member="HOADONs" ThisKey="MAPSC" OtherKey="MAPSC" Type="HOADON" />
      <Association Name="NHANVIEN_PHIEUSUACHUA" Member="NHANVIEN" ThisKey="MANHANVIENTIEPNHAN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUSUACHUA1" Member="NHANVIEN1" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUSUACHUA2" Member="NHANVIEN2" ThisKey="NGUOIGOI" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUTIEPNHAN_PHIEUSUACHUA" Member="PHIEUTIEPNHAN" ThisKey="MAPHIEUTN" OtherKey="MAPHIEUTN" Type="PHIEUTIEPNHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTIEPNHAN" Member="PHIEUTIEPNHANs">
    <Type Name="PHIEUTIEPNHAN">
      <Column Name="MAPHIEUTN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATHIETBI" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANHANVIEN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAKHACHKHACH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYNHAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYHENTRA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TINHHINHHUHONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PHUKIENKEMTHEO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HINHTHUC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GHICHUPTN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="XOA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHIEUTIEPNHAN_CHITIETTN" Member="CHITIETTNs" ThisKey="MAPHIEUTN" OtherKey="MAPHIEUTN" Type="CHITIETTN" />
      <Association Name="PHIEUTIEPNHAN_PHIEUSUACHUA" Member="PHIEUSUACHUAs" ThisKey="MAPHIEUTN" OtherKey="MAPHIEUTN" Type="PHIEUSUACHUA" />
      <Association Name="KHACHHANG_PHIEUTIEPNHAN" Member="KHACHHANG" ThisKey="MAKHACHKHACH" OtherKey="MAKHACHKHACH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="THIETBI_PHIEUTIEPNHAN" Member="THIETBI" ThisKey="MATHIETBI" OtherKey="MATHIETBI" Type="THIETBI" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUTIEPNHAN" Member="NHANVIEN" ThisKey="MANHANVIEN" OtherKey="MANHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>