//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPTN
    {
        public string MAPHIEUTN { get; set; }
        public string MAKHACHKHACH { get; set; }
        public Nullable<System.DateTime> NGAYNHAN { get; set; }
        public Nullable<System.DateTime> NGAYHENTRA { get; set; }
        public string TINHHINHHUHONG { get; set; }
        public string PHUKIENKEMTHEO { get; set; }
        public string GHICHUPTN { get; set; }
    }
}
