//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHD
    {
        public string MAHOADON { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUCBH { get; set; }
        public Nullable<decimal> GIATHANH { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string Expr1 { get; set; }
        public string TENKHACHHANG { get; set; }
        public string TENNHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string TENLINHKIEN { get; set; }
        public string MALINHKIEN { get; set; }
    }
}
